### ISSUE TITLE
Doesn't install on rpi4 with raspbian buster. 

### ISSUE THREAD

**Issue by dmurphydrtc** [tryffel/jellycli#1]
![Screenshot_20200301-162721](https://user-images.githubusercontent.com/5334819/75620218-33e70e00-5bda-11ea-877b-39c58a190a9d.jpg)
Btw... thanks a million for this utility.

**Comment by tryffel** [comment]
Ok, first, you need go version 1.13. 
Second, due to go-import alias you first need to
```
go get -u tryffel.net/go/jellycli
```
This will warn you 'no go files in ..', then
```
go get -u tryffel.net/go/jellycli/cmd
```
Now it should work. I will look into these.

**Comment by dmurphydrtc** [comment]
Will check out tomorrow and report back. Thanks for the prompt response and your willingness to share your software.

**Comment by dmurphydrtc** [comment]
Managed to get it software installed and configured. But not seeing any of my music when envoke the program. Any ideas? Obviously I can play and view all music using jellyfin.
.
[print.pdf](https://github.com/tryffel/jellycli/files/4275330/print.pdf)

**Comment by tryffel** [comment]
Next, select what you want to listen to. Use tab to activate left-hand-side panel and from there select any enabled option (e.g. latest albums, favorite artists). And F1 shows help page, which has some info on shortcuts to use. Sorry, navigation is still a bit mess even though I have tried to make it as intuitive as possible. Basically all navigation is done with tab, arrows, vim-keys and function keys (often times multiple of these are valid).

**Comment by dmurphydrtc** [comment]
Great..got sorted.
