### ISSUE TITLE
Re-licensing to gpl-v3

### ISSUE THREAD

**Issue by tryffel** [tryffel/jellycli#11]
I have spent some time building this software, and will likely continue doing that. With each new feature it makes more sense to re-license Jellycli to gpl. @leonardochaia, since you have contributed to this project, are you ok with re-licensing to GPL-v3? (Currently license is Apache-2).

**Comment by leonardochaia** [comment]
Hi @tryffel appreciate you asking me before doing the change.

Personally I have no issues whatsoever with licensing to GPL-v3! Go ahead.

Have a good one!
Leo.
