### ISSUE TITLE
hanging after choosing music view

### ISSUE THREAD

**Issue by bitva77** [tryffel/jellycli#15]
```
bitva@media:~$ ./jellycli_0.8.0_Linux_x86_64 --no-gui
WARN[0000] Create new config file /home/bitva/.config/jellycli.yaml
[12:42:51.470]  INFO ############# Jellycli v0.8.0 ############
Enter jellyfin host: http://192.168.1.7:8096/
Enter Username: media
Enter Password:
Found collections:
1. Live TV (UserView)
2. Movies (CollectionFolder)
3. Music (CollectionFolder)
4. TV Shows (CollectionFolder)
Enter Default music view (enter number): 3
[12:43:11.536]  INFO Websocket encryption disabled
```

Now, it is doing something as I see it's CPU usage stay at a few percent.  I have quite a big music library.  Is it trying to scan it (or something?)

Thanks!

**Comment by tryffel** [comment]
It's not scanning anything, it is waiting for commands from server. Try to queue something from Jellyfin UI. =)

**Comment by bitva77** [comment]
OH.  well I'm an idiot.  lol.  will mess with it later when I can verify it playing :)

**Comment by tryffel** [comment]
Maybe I should add some log message for 'waiting command' or 'ready' etc..
