### ISSUE TITLE
First run quits with error related to config file

### ISSUE THREAD

**Issue by campyne** [tryffel/jellycli#18]
Hello,
When running `jellycli` for the first time, the program quits with the following:

``` 
WARN[0000] Create new config file /home/myuser/.config/jellycli.yaml 
ERRO[0000] save config file: save config file: open /home/myuser/.config/jellycli/jellycli.yaml: no such file or directory 
FATA[0000] save config file: save config file: open /home/myuser/.config/jellycli/jellycli.yaml: no such file or directory
```

After taking a look, it seems to me that the issue is in `config/file.go` where it uses `dir, err = os.UserConfigDir()` to get the directory for all configs `/home/myuser/.config` and doesn't then add the appropriate sub-directory `jellycli` to it.

**Comment by tryffel** [comment]
Yes, it certainly seems so. Luckily it should be an easy fix, just create the directory manually for now.
