### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by uGeek** [tryffel/jellycli#2]
Where is the configuration file? I've put another server and it doesn't let me

Thanks!

**Comment by tryffel** [comment]
Currently there is no config file. All needed info is stored in keyring. Easiest way would be to just delete Jellycli from keyring and then re-enter those when running Jellycli. Or do you mean you would be using multiple servers and would need separate profile for each?

**Comment by tryffel** [comment]
Just fyi, with release 0.2, Jellycli now uses configuration file instead of keyring. Each config file is per-server / per-user. You can use multiple config files.

**Comment by uGeek** [comment]
Great app!!!. 
With the configuration file it is much easier and also allows having multiple servers.

I have created an article on my blog and next week I will speak on my podcast.
https://ugeek.github.io/blog/post/2020-03-10-escuchando-musica-de-mi-servidor-jellyfin-con-jellycli.html

Thank you very much for your work

**Comment by tryffel** [comment]
> Great app!!!.
> With the configuration file it is much easier and also allows having multiple servers.
> 
> I have created an article on my blog and next week I will speak on my podcast.
> https://ugeek.github.io/blog/post/2020-03-10-escuchando-musica-de-mi-servidor-jellyfin-con-jellycli.html
> 
> Thank you very much for your work

Thank you for support, this is just great! :smile:

**Comment by leonardochaia** [comment]
Hi @tryffel , sorry to hijack this issue.

Would you consider replacing the current config file implementation with [viper](https://github.com/spf13/viper)? This would be quite useful to support multiple configuration sources. Ideally one could support multiple files like most common OSes paths, and environmental variables.

Environmental variables are quite useful when spinning up docker containers. (I'm u/leonardochaia)

**Comment by brandonxoliver** [comment]
can you post an example of the config file? I keep getting a login failed error when creating one for the first time.

**Comment by leonardochaia** [comment]
Jellycli will create the config file for you on first usage, if a config file is not detected. You can change the path by using the `-config` flag. The default path is `/root/.config` apparently.

Here's my config file. I don't think it's intended to be edited manually except perhaps for the url
```yaml
server_url: https://your-jellyfin.homelab.net
username: ""
token: <token here>
user_id: <user_id here>
device_id: <device_id here>
server_id: <server_id here>
music_view: <music id here>

```

**Comment by tryffel** [comment]
@brandonxoliver: The config file provided by Leonardochaia is correct for version 0.2.0. And for me the server url is https://host/jellyfin. Do you get any errors other than login failed? Which os / go version are you using? 'Login failed' should be as simple as it is. However, I noticed that reading password from windows atm results in strange output, that is, lot's of spaces around characters.

**Comment by tryffel** [comment]
> Hi @tryffel , sorry to hijack this issue.
> 
> Would you consider replacing the current config file implementation with [viper](https://github.com/spf13/viper)? This would be quite useful to support multiple configuration sources. Ideally one could support multiple files like most common OSes paths, and environmental variables.
> 
> Environmental variables are quite useful when spinning up docker containers. (I'm u/leonardochaia)

I haven't really used viper, so it might take a while to properly use it in this case. I can definitely think about it though. For now (simple cases), using args has been working well, but maybe it's not sufficient for docker images anymore.

**Comment by tryffel** [comment]
> Hi @tryffel , sorry to hijack this issue.
> 
> Would you consider replacing the current config file implementation with [viper](https://github.com/spf13/viper)? This would be quite useful to support multiple configuration sources. Ideally one could support multiple files like most common OSes paths, and environmental variables.
> 
> Environmental variables are quite useful when spinning up docker containers. (I'm u/leonardochaia)

@leonardochaia, thinking of viper, the ids present in config file right now need to be persisted somehow. How would viper implement this? Or would use case be to always use config file for persistence, and then override any values with e.g. env vars? Could you show some concrete examples of viper benefiting Jellycli, for docker or for ordinary cli use? Thanks!

**Comment by leonardochaia** [comment]
Hi, I think that viper may be useful for the configuration that the user is able to edit. 
Viper abstract away the origin of the config, meaning that the config may come from environment, config file, or other methods like key/value store. Most of the code doesn't know where the config is coming from, only how to access it. Only the CLI layer would call to viper's methods for reading from environment and config file or files.

I haven't really looked at the code, but perhaps if it's possible not to store autocalculated fields, like the device and server id? It'd be good to be able to override these fields but there's no need to persist the auto calculated ones, we can just calculate them again

For the access token, I think a native credential store may be better. But I'm not sure about this one, perhaps we can check what other apps do with these. 

For the server url, username and library it'd be useful to be able to configure it through environment variables.

Particularly for Docker, if the image supports env vars, you can provide them when creating the container which simplifies the steps required when creating the container.

This way you don't need to interact with the CLI when starting the container which becomes particularly useful for headless mode:
```yml
version: 3.7
services:
   jellycli:
      image: tryffel/jellycli
      env:
         JELLYCLI_SERVER: https://myjellyfin.example.com
         JELLYCLI_USERNAME: jellycliplayer
         JELLYCLI_PASSWORD: jellycliplayer123123
         JELLYCLI_HEADLESS: 'true'
```
Personally I wouldn't mind having the password stored in plaintext, considering that it will be used in a LAN and for play only access rights.

**Comment by tryffel** [comment]
Sorry @leonardochaia for taking so long. I have been busy with other tasks and also I have been thinking this many times and still haven't completely decided which solution would be the best way to continue. Surely env variables would be nice, but I tried using Viper for supplementing config file with env vars, and while it's pretty straightforward, it takes some time to manually map all the values (and keep them updated). As I understand it, with Viper, env variables are not automatically overriding config file, but you have to manually query each config value and write them to config struct. But then it's also all-in when using Viper, e.g. I must rewrite the whole config part of the application to benefit from Viper.

On the other hand, isn't this possible by just mounting a docker volume with config file to jellycli? And I could add a config value (or just JELLYCLI_NO_GUI env var) for now. Would that make it easier to use and be sufficient for now?

**Comment by leonardochaia** [comment]
Hi @tryffel , no problem. I'm also caught up in work right now.

Anyways, regarding viper, [check my implementation here](https://github.com/leonardochaia/vendopunkto/blob/a71e659688ba01bcf23843bdddc68ccf92b5d57f/internal/conf/runtime-conf.go#L47)

What I do is bind the config to a struct and then inject that struct where the config is needed, I don't really know if the value is coming from env, config, or other. Viper takes care of that.

It is possible to mount a file and it would make it easier yes.
But take into account that in that case, you can't provide a simple `docker run` command, since you also need a config file. Being able to provide (at least essential) config through envs makes it easier to quickly spin up the container for testing and stuff. For prod it's also good,cause you can keep the container config together with the "docker" config in the `docker-compose.yml` file.

For example, if I tell you:

You can run jellycli like this:
```bash
docker run -it --rm -e JELLYCLI_SERVER: https://myjellyfin.example.com \
-e  JELLYCLI_USERNAME: jellycliplayer
-e JELLYCLI_PASSWORD: jellycliplayer123123
-e JELLYCLI_HEADLESS: 'true'
```

or like this:
```yml
version: 3.7
services:
   jellycli:
      image: tryffel/jellycli
      env:
         JELLYCLI_SERVER: https://myjellyfin.example.com
         JELLYCLI_USERNAME: jellycliplayer
         JELLYCLI_PASSWORD: jellycliplayer123123
         JELLYCLI_HEADLESS: 'true'
```
and  then simply
```bash
docker-compose up -d
```

It's IMHO a better API than

You need this command
```bash
docker run -it --rm -v /path/to/your/config:/config
```
and also this config file, which needs to be placed at the path that you need to replace on the -v there. But watch it, if you need to move the container to another environment, you also need to move the config file! 
[...]

I think you've got my point. It's a dumb point? maybe, but in the end, the lower the barrier for using an app the better.

In the end, I think that both are good as far as you have a way for configuring the things you care.
BTW, Mounting a file is probably more secure for the password since it's not on the container's environment and can be secured with permissions. In the end its all about tradeoffs.
