### ISSUE TITLE
Request: how to configure navbar grid to remove leading space?

### ISSUE THREAD

**Issue by vlfldr** [tryffel/jellycli#25]
Hello - where in the code would one look to align the beginning of the navbar ("F1 Help") directly above the sidebar as opposed to over the main panel? Great program, cheers!

**Comment by tryffel** [comment]
Hi, the relevant lines are actually located in the repositoy https://github.com/tryffel/twidgets.

I think the relevant function is https://github.com/tryffel/twidgets/blob/master/navbar.go#L144.
