### ISSUE TITLE
Cannot Connect to Server

### ISSUE THREAD

**Issue by billotronic** [tryffel/jellycli#33]
I've tried docker and compiling from source on a rp2. Both get to the login portion of starting and I get this error:

`[16:05:52.154] FATAL connect to server: api init: parse url: parse "192.168.0.104:8096": first path segment in URL cannot contain colon
`

Same result if I put the URL in the conf

go version go1.17.6 linux/arm

Thanks for this project.

**Comment by tryffel** [comment]
Can you try adding the prefix http:// or https://, respectively?
