### ISSUE TITLE
Error connecting to Navidrome server

### ISSUE THREAD

**Issue by Bubbu0129** [tryffel/jellycli#39]
After install jellycli on windows, I encountered this error:
`FATAL connect to server: api init: invalid character '<' looking for beginning of value`

Platform: Windows 11 x86-64
Server: Navidrome 0.47.5
config: 
`player: server: subsonic`
url and username are filled but salt and token are empty.
Should I fill them? If so, how?

**Comment by tryffel** [comment]
Could you se the logging level to debug? Does it print anything else? Are you sure the entered path is correct?
It needs to be in format `https://<domain>/path`.

**Comment by Bubbu0129** [comment]
Solved.
I used `https://<domain>/path/` so it wasn't working.
Didn't spot this format discription in the documentation though. Maybe add some guidance?
