### ISSUE TITLE
armhf Build (Raspberry Pi Zero W)

### ISSUE THREAD

**Issue by joshaspinall** [tryffel/jellycli#50]
Requires alsa-tools.

Build terminates with the following:

`joshua@pizerow:~/go/src/tryffel.net/go/jellycli $ go build .`
`# tryffel.net/go/jellycli/util`
`util/browser_macos.go:21:5: browserOpenUrl redeclared in this block`
`	previous declaration at util/browser_linux.go:21:5`

**Comment by tryffel** [comment]
yeah, there's a bug in the master branch related to #48 . You can try checking out one commit before the latest and build that one instead. (2ffd1839ceb2121c801a928dac580a364eacad56)

**Comment by joshaspinall** [comment]
Built successfully and works a treat.  Keep up the good work! 👍🏻
