### ISSUE TITLE
Search for title

### ISSUE THREAD

**Issue by patrickpichler** [tryffel/jellycli#9]
I've read through the documentation, but didn't find any mention of search.

Is there currently the possibility to search for songs?

**Comment by tryffel** [comment]
You're correct, there is no search at the moment. It's been on the todo-list for a while now and I haven't yet settled on what it should look like. How would you like it to work? I can think of two ways: 1. create a modal for searching, and select what types are looking for (albums, playlists), or 2. similar to webui, just list any kind of matching content.

**Comment by patrickpichler** [comment]
I have no idea what the jellyfin api looks like, but something like the search from the (spotify-tui)[https://github.com/Rigellute/spotify-tui] project would be nice.

If I have some time over the weekend I might do a prototype to test a few layouts.

**Comment by tryffel** [comment]
Search is implemented in version [v0.7.0](https://github.com/tryffel/jellycli/releases/tag/v0.7.0).
